// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFlg8Lwb9A0b_TwpBCsUTuOfMHn9LzpM',
    appId: '1:590848379222:web:10b16dcdd967abd831aef7',
    messagingSenderId: '590848379222',
    projectId: 'fooddelivery-6c023',
    authDomain: 'fooddelivery-6c023.firebaseapp.com',
    storageBucket: 'fooddelivery-6c023.appspot.com',
    measurementId: 'G-BMLN35G00K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwrtInQvn2-ghoJMpnlA6tc09pTcy7tE',
    appId: '1:590848379222:android:1fc6bcffcd969c9731aef7',
    messagingSenderId: '590848379222',
    projectId: 'fooddelivery-6c023',
    storageBucket: 'fooddelivery-6c023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KU1XES9uK6T3csB9_6faCYXaYGkfIaE',
    appId: '1:590848379222:ios:35906c37427d054d31aef7',
    messagingSenderId: '590848379222',
    projectId: 'fooddelivery-6c023',
    storageBucket: 'fooddelivery-6c023.appspot.com',
    iosClientId: '590848379222-vttpfbi6f3f4p7h1gs0oapdqqfk793lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9KU1XES9uK6T3csB9_6faCYXaYGkfIaE',
    appId: '1:590848379222:ios:35906c37427d054d31aef7',
    messagingSenderId: '590848379222',
    projectId: 'fooddelivery-6c023',
    storageBucket: 'fooddelivery-6c023.appspot.com',
    iosClientId: '590848379222-vttpfbi6f3f4p7h1gs0oapdqqfk793lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodserve',
  );
}
